#This file is auto generated from /regression_suite/size_scaling.html
#The html examples and tutorial are the source of truth and are far more readable and beneficial. Start there (see readme for how).
#Use these r files for reference, but know that some instructional content is not transferred from the html to the r examples files
#TL;DR View the tutorial/example the way it was meant to be: in HTML format!

#Intro
##This set of examples provides a tool to verify that the size scaling technique is handled correctly in a variety of situations.

#Circle
rhtmlPictographs::graphic('{ "proportion": "=0.5 + 1/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "circle:scale:lightblue", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "proportion": "=0.5 + 2/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "circle:scale:lightblue", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "proportion": "=0.5 + 3/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "circle:scale:lightblue", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "proportion": "=0.5 + 4/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "circle:scale:lightblue", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "proportion": "=0.5 + 5/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "circle:scale:lightblue", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "proportion": "=0.5 + 6/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "circle:scale:lightblue", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "proportion": "=0.5 + 7/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "circle:scale:lightblue", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "proportion": "=0.5 + 8/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "circle:scale:lightblue", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "proportion": "=0.5 + 9/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "circle:scale:lightblue", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "proportion": "=0.5 + 10/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "circle:scale:lightblue", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "proportion": "=0.5 + 11/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "circle:scale:lightblue", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "proportion": "=0.5 + 12/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "circle:scale:lightblue", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "proportion": "=0.5 + 13/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "circle:scale:lightblue", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "proportion": "=0.5 + 14/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "circle:scale:lightblue", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "proportion": "=0.5 + 15/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "circle:scale:lightblue", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "proportion": "=0.5 + 16/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "circle:scale:lightblue", "background-color": "#dddddd" }')

#Circle in Rectangle
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 1/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "circle:scale:lightblue", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 2/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "circle:scale:lightblue", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 3/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "circle:scale:lightblue", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 4/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "circle:scale:lightblue", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 5/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "circle:scale:lightblue", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 6/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "circle:scale:lightblue", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 7/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "circle:scale:lightblue", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 8/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "circle:scale:lightblue", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 9/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "circle:scale:lightblue", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 10/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "circle:scale:lightblue", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 11/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "circle:scale:lightblue", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 12/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "circle:scale:lightblue", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 13/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "circle:scale:lightblue", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 14/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "circle:scale:lightblue", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 15/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "circle:scale:lightblue", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 16/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "circle:scale:lightblue", "background-color": "#dddddd" }')

#Ellipse in Rectangle
rhtmlPictographs::graphic('{ "proportion": "=0.5 + 1/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "ellipse:scale:lightblue", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "proportion": "=0.5 + 2/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "ellipse:scale:lightblue", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "proportion": "=0.5 + 3/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "ellipse:scale:lightblue", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "proportion": "=0.5 + 4/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "ellipse:scale:lightblue", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "proportion": "=0.5 + 5/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "ellipse:scale:lightblue", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "proportion": "=0.5 + 6/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "ellipse:scale:lightblue", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "proportion": "=0.5 + 7/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "ellipse:scale:lightblue", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "proportion": "=0.5 + 8/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "ellipse:scale:lightblue", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "proportion": "=0.5 + 9/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "ellipse:scale:lightblue", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "proportion": "=0.5 + 10/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "ellipse:scale:lightblue", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "proportion": "=0.5 + 11/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "ellipse:scale:lightblue", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "proportion": "=0.5 + 12/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "ellipse:scale:lightblue", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "proportion": "=0.5 + 13/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "ellipse:scale:lightblue", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "proportion": "=0.5 + 14/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "ellipse:scale:lightblue", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "proportion": "=0.5 + 15/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "ellipse:scale:lightblue", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "proportion": "=0.5 + 16/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "ellipse:scale:lightblue", "background-color": "#dddddd" }')

#External SVG Image in Rectangle With Different Aspect Ratio
##This shows a limitation of scaling an external image that doesn't "fit" the cell.
##In these examples a cell of 200x100 (or 100x200) contains an external image of a circle, which is scaled to fit such that the circle has a diameter of 100 and is centred in the cell.
##The issue is there is no way to now what proportion of the cell is occupied by the image, so the scaling takes place accross the entire cell, not just for the content occupied by the image.
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 1/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:/images/blue_circle_512.svg", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 2/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:/images/blue_circle_512.svg", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 3/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:/images/blue_circle_512.svg", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 4/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:/images/blue_circle_512.svg", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 5/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:/images/blue_circle_512.svg", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 6/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:/images/blue_circle_512.svg", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 7/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:/images/blue_circle_512.svg", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 8/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:/images/blue_circle_512.svg", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 9/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:/images/blue_circle_512.svg", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 10/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:/images/blue_circle_512.svg", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 11/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:/images/blue_circle_512.svg", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 12/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:/images/blue_circle_512.svg", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 13/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:/images/blue_circle_512.svg", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 14/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:/images/blue_circle_512.svg", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 15/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:/images/blue_circle_512.svg", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 16/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:/images/blue_circle_512.svg", "background-color": "#dddddd" }')

#External Recolored SVG Image in Rectangle With Different Aspect Ratio
##Same issue as above.
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 1/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:red:/images/blue_circle_512.svg", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 2/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:red:/images/blue_circle_512.svg", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 3/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:red:/images/blue_circle_512.svg", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 4/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:red:/images/blue_circle_512.svg", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 5/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:red:/images/blue_circle_512.svg", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 6/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:red:/images/blue_circle_512.svg", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 7/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:red:/images/blue_circle_512.svg", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 8/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:red:/images/blue_circle_512.svg", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 9/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:red:/images/blue_circle_512.svg", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 10/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:red:/images/blue_circle_512.svg", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 11/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:red:/images/blue_circle_512.svg", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 12/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:red:/images/blue_circle_512.svg", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 13/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:red:/images/blue_circle_512.svg", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 14/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:red:/images/blue_circle_512.svg", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 15/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:red:/images/blue_circle_512.svg", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 16/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:red:/images/blue_circle_512.svg", "background-color": "#dddddd" }')

#(Single Image) External Recolored SVG Image in Rectangle With Different Aspect Ratio
##Same issue as above.
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=1/16", "columnGutter": "0", "numImages": 1, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:red:/images/blue_circle_512.svg", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=2/16", "columnGutter": "0", "numImages": 1, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:red:/images/blue_circle_512.svg", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=3/16", "columnGutter": "0", "numImages": 1, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:red:/images/blue_circle_512.svg", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=4/16", "columnGutter": "0", "numImages": 1, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:red:/images/blue_circle_512.svg", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=5/16", "columnGutter": "0", "numImages": 1, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:red:/images/blue_circle_512.svg", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=6/16", "columnGutter": "0", "numImages": 1, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:red:/images/blue_circle_512.svg", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=7/16", "columnGutter": "0", "numImages": 1, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:red:/images/blue_circle_512.svg", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=8/16", "columnGutter": "0", "numImages": 1, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:red:/images/blue_circle_512.svg", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=9/16", "columnGutter": "0", "numImages": 1, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:red:/images/blue_circle_512.svg", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=10/16", "columnGutter": "0", "numImages": 1, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:red:/images/blue_circle_512.svg", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=11/16", "columnGutter": "0", "numImages": 1, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:red:/images/blue_circle_512.svg", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=12/16", "columnGutter": "0", "numImages": 1, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:red:/images/blue_circle_512.svg", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=13/16", "columnGutter": "0", "numImages": 1, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:red:/images/blue_circle_512.svg", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=14/16", "columnGutter": "0", "numImages": 1, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:red:/images/blue_circle_512.svg", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=15/16", "columnGutter": "0", "numImages": 1, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:red:/images/blue_circle_512.svg", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=16/16", "columnGutter": "0", "numImages": 1, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:red:/images/blue_circle_512.svg", "background-color": "#dddddd" }')

#External PNG Image in Rectangle With Different Aspect Ratio
##Same issue as above.
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 1/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:/images/blue_circle_512.png", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 2/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:/images/blue_circle_512.png", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 3/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:/images/blue_circle_512.png", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 4/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:/images/blue_circle_512.png", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 5/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:/images/blue_circle_512.png", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 6/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:/images/blue_circle_512.png", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 7/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:/images/blue_circle_512.png", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 8/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:/images/blue_circle_512.png", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 9/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:/images/blue_circle_512.png", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 10/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:/images/blue_circle_512.png", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 11/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:/images/blue_circle_512.png", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 12/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:/images/blue_circle_512.png", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 13/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:/images/blue_circle_512.png", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 14/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:/images/blue_circle_512.png", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 15/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:/images/blue_circle_512.png", "background-color": "#dddddd" }')
rhtmlPictographs::graphic('{ "debugBorder": "true", "proportion": "=0.5 + 16/32", "columnGutter": "0", "numImages": 2, "text-footer": { "text": "percentage", "font-size": "12" }, "variableImage": "url:scale:/images/blue_circle_512.png", "background-color": "#dddddd" }')
