#This file is auto generated from /content/regression_suite/url_preserve_aspect_ratios.html
#The html examples and tutorial are the source of truth and are far more readable and beneficial. Start there (see readme for how).
#Use these r files for reference, but know that some instructional content is not transferred from the html to the r examples files
#TL;DR View the tutorial/example the way it was meant to be: in HTML format!

rhtmlPictographs::graphic('{ "text-footer": { "text": "1", "font-size": "50px" }, "variableImage": "url:/images/green_rectangle_600_900.jpg", "background-color": "yellow", "image-background-color": "pink", "resizable": "false"}')
rhtmlPictographs::graphic('{ "text-footer": { "text": "2", "font-size": "50px" }, "variableImage": "url:/images/green_rectangle_600_900.jpg", "background-color": "yellow", "image-background-color": "pink", "resizable": "false"}')
rhtmlPictographs::graphic('{ "text-footer": { "text": "3", "font-size": "50px" }, "variableImage": { "preserveAspectRatio": "xMidYMid slice", "type": "url", "url": "/images/green_rectangle_600_900.jpg" }, "background-color": "yellow", "image-background-color": "pink", "resizable": "false"}')
rhtmlPictographs::graphic('{ "text-footer": { "text": "4", "font-size": "50px" }, "variableImage": { "preserveAspectRatio": "xMidYMin meet", "type": "url", "url": "/images/green_rectangle_600_900.jpg" }, "background-color": "yellow", "image-background-color": "pink", "resizable": "false"}')
rhtmlPictographs::graphic('{ "text-footer": { "text": "5", "font-size": "50px" }, "variableImage": { "preserveAspectRatio": "xMidYMax meet", "type": "url", "url": "/images/green_rectangle_600_900.jpg" }, "background-color": "yellow", "image-background-color": "pink", "resizable": "false"}')
rhtmlPictographs::graphic('{ "text-footer": { "text": "6", "font-size": "50px" }, "variableImage": { "preserveAspectRatio": "xMinYMid meet", "type": "url", "url": "/images/green_rectangle_600_900.jpg" }, "background-color": "yellow", "image-background-color": "pink", "resizable": "false"}')
rhtmlPictographs::graphic('{ "text-footer": { "text": "7", "font-size": "50px" }, "variableImage": { "preserveAspectRatio": "xMaxYMid meet", "type": "url", "url": "/images/green_rectangle_600_900.jpg" }, "background-color": "yellow", "image-background-color": "pink", "resizable": "false"}')

rhtmlPictographs::graphic('{ "text-footer": { "text": "1", "font-size": "50px" }, "proportion": "0.33", "variableImage": "url:fromleft:/images/green_rectangle_600_900.jpg", "background-color": "yellow", "image-background-color": "pink", "resizable": "false"}')
rhtmlPictographs::graphic('{ "text-footer": { "text": "2", "font-size": "50px" }, "proportion": "0.33", "variableImage": "url:fromleft:/images/green_rectangle_600_900.jpg", "background-color": "yellow", "image-background-color": "pink", "resizable": "false"}')
rhtmlPictographs::graphic('{ "text-footer": { "text": "3", "font-size": "50px" }, "proportion": "0.33", "variableImage": { "clip": "fromleft", "preserveAspectRatio": "xMidYMid slice", "type": "url", "url": "/images/green_rectangle_600_900.jpg" }, "background-color": "yellow", "image-background-color": "pink", "resizable": "false"}')
rhtmlPictographs::graphic('{ "text-footer": { "text": "4", "font-size": "50px" }, "proportion": "0.33", "variableImage": { "clip": "fromleft", "preserveAspectRatio": "xMidYMin meet", "type": "url", "url": "/images/green_rectangle_600_900.jpg" }, "background-color": "yellow", "image-background-color": "pink", "resizable": "false"}')
rhtmlPictographs::graphic('{ "text-footer": { "text": "5", "font-size": "50px" }, "proportion": "0.33", "variableImage": { "clip": "fromleft", "preserveAspectRatio": "xMidYMax meet", "type": "url", "url": "/images/green_rectangle_600_900.jpg" }, "background-color": "yellow", "image-background-color": "pink", "resizable": "false"}')
rhtmlPictographs::graphic('{ "text-footer": { "text": "6", "font-size": "50px" }, "proportion": "0.33", "variableImage": { "clip": "fromleft", "preserveAspectRatio": "xMinYMid meet", "type": "url", "url": "/images/green_rectangle_600_900.jpg" }, "background-color": "yellow", "image-background-color": "pink", "resizable": "false"}')
rhtmlPictographs::graphic('{ "text-footer": { "text": "7", "font-size": "50px" }, "proportion": "0.33", "variableImage": { "clip": "fromleft", "preserveAspectRatio": "xMaxYMid meet", "type": "url", "url": "/images/green_rectangle_600_900.jpg" }, "background-color": "yellow", "image-background-color": "pink", "resizable": "false"}')

rhtmlPictographs::graphic('{ "text-footer": { "text": "1", "font-size": "50px" }, "proportion": "0.33", "variableImage": "url:fromtop:/images/green_rectangle_600_900.jpg", "background-color": "yellow", "image-background-color": "pink", "resizable": "false"}')
rhtmlPictographs::graphic('{ "text-footer": { "text": "2", "font-size": "50px" }, "proportion": "0.33", "variableImage": "url:fromtop:/images/green_rectangle_600_900.jpg", "background-color": "yellow", "image-background-color": "pink", "resizable": "false"}')
rhtmlPictographs::graphic('{ "text-footer": { "text": "3", "font-size": "50px" }, "proportion": "0.33", "variableImage": { "clip": "fromtop", "preserveAspectRatio": "xMidYMid slice", "type": "url", "url": "/images/green_rectangle_600_900.jpg" }, "background-color": "yellow", "image-background-color": "pink", "resizable": "false"}')
rhtmlPictographs::graphic('{ "text-footer": { "text": "4", "font-size": "50px" }, "proportion": "0.33", "variableImage": { "clip": "fromtop", "preserveAspectRatio": "xMidYMin meet", "type": "url", "url": "/images/green_rectangle_600_900.jpg" }, "background-color": "yellow", "image-background-color": "pink", "resizable": "false"}')
rhtmlPictographs::graphic('{ "text-footer": { "text": "5", "font-size": "50px" }, "proportion": "0.33", "variableImage": { "clip": "fromtop", "preserveAspectRatio": "xMidYMax meet", "type": "url", "url": "/images/green_rectangle_600_900.jpg" }, "background-color": "yellow", "image-background-color": "pink", "resizable": "false"}')
rhtmlPictographs::graphic('{ "text-footer": { "text": "6", "font-size": "50px" }, "proportion": "0.33", "variableImage": { "clip": "fromtop", "preserveAspectRatio": "xMinYMid meet", "type": "url", "url": "/images/green_rectangle_600_900.jpg" }, "background-color": "yellow", "image-background-color": "pink", "resizable": "false"}')
rhtmlPictographs::graphic('{ "text-footer": { "text": "7", "font-size": "50px" }, "proportion": "0.33", "variableImage": { "clip": "fromtop", "preserveAspectRatio": "xMaxYMid meet", "type": "url", "url": "/images/green_rectangle_600_900.jpg" }, "background-color": "yellow", "image-background-color": "pink", "resizable": "false"}')

rhtmlPictographs::graphic('{ "text-footer": { "text": "1", "font-size": "50px" }, "proportion": "0.33", "variableImage": "url:frombottom:/images/green_rectangle_600_900.jpg", "background-color": "yellow", "image-background-color": "pink", "resizable": "false"}')
rhtmlPictographs::graphic('{ "text-footer": { "text": "2", "font-size": "50px" }, "proportion": "0.33", "variableImage": "url:frombottom:/images/green_rectangle_600_900.jpg", "background-color": "yellow", "image-background-color": "pink", "resizable": "false"}')
rhtmlPictographs::graphic('{ "text-footer": { "text": "3", "font-size": "50px" }, "proportion": "0.33", "variableImage": { "clip": "frombottom", "preserveAspectRatio": "xMidYMid slice", "type": "url", "url": "/images/green_rectangle_600_900.jpg" }, "background-color": "yellow", "image-background-color": "pink", "resizable": "false"}')
rhtmlPictographs::graphic('{ "text-footer": { "text": "4", "font-size": "50px" }, "proportion": "0.33", "variableImage": { "clip": "frombottom", "preserveAspectRatio": "xMidYMin meet", "type": "url", "url": "/images/green_rectangle_600_900.jpg" }, "background-color": "yellow", "image-background-color": "pink", "resizable": "false"}')
rhtmlPictographs::graphic('{ "text-footer": { "text": "5", "font-size": "50px" }, "proportion": "0.33", "variableImage": { "clip": "frombottom", "preserveAspectRatio": "xMidYMax meet", "type": "url", "url": "/images/green_rectangle_600_900.jpg" }, "background-color": "yellow", "image-background-color": "pink", "resizable": "false"}')
rhtmlPictographs::graphic('{ "text-footer": { "text": "6", "font-size": "50px" }, "proportion": "0.33", "variableImage": { "clip": "frombottom", "preserveAspectRatio": "xMinYMid meet", "type": "url", "url": "/images/green_rectangle_600_900.jpg" }, "background-color": "yellow", "image-background-color": "pink", "resizable": "false"}')
rhtmlPictographs::graphic('{ "text-footer": { "text": "7", "font-size": "50px" }, "proportion": "0.33", "variableImage": { "clip": "frombottom", "preserveAspectRatio": "xMaxYMid meet", "type": "url", "url": "/images/green_rectangle_600_900.jpg" }, "background-color": "yellow", "image-background-color": "pink", "resizable": "false"}')

rhtmlPictographs::graphic('{ "text-footer": { "text": "1", "font-size": "50px" }, "proportion": "0.33", "variableImage": "url:fromright:/images/green_rectangle_600_900.jpg", "background-color": "yellow", "image-background-color": "pink", "resizable": "false"}')
rhtmlPictographs::graphic('{ "text-footer": { "text": "2", "font-size": "50px" }, "proportion": "0.33", "variableImage": "url:fromright:/images/green_rectangle_600_900.jpg", "background-color": "yellow", "image-background-color": "pink", "resizable": "false"}')
rhtmlPictographs::graphic('{ "text-footer": { "text": "3", "font-size": "50px" }, "proportion": "0.33", "variableImage": { "clip": "fromright", "preserveAspectRatio": "xMidYMid slice", "type": "url", "url": "/images/green_rectangle_600_900.jpg" }, "background-color": "yellow", "image-background-color": "pink", "resizable": "false"}')
rhtmlPictographs::graphic('{ "text-footer": { "text": "4", "font-size": "50px" }, "proportion": "0.33", "variableImage": { "clip": "fromright", "preserveAspectRatio": "xMidYMin meet", "type": "url", "url": "/images/green_rectangle_600_900.jpg" }, "background-color": "yellow", "image-background-color": "pink", "resizable": "false"}')
rhtmlPictographs::graphic('{ "text-footer": { "text": "5", "font-size": "50px" }, "proportion": "0.33", "variableImage": { "clip": "fromright", "preserveAspectRatio": "xMidYMax meet", "type": "url", "url": "/images/green_rectangle_600_900.jpg" }, "background-color": "yellow", "image-background-color": "pink", "resizable": "false"}')
rhtmlPictographs::graphic('{ "text-footer": { "text": "6", "font-size": "50px" }, "proportion": "0.33", "variableImage": { "clip": "fromright", "preserveAspectRatio": "xMinYMid meet", "type": "url", "url": "/images/green_rectangle_600_900.jpg" }, "background-color": "yellow", "image-background-color": "pink", "resizable": "false"}')
rhtmlPictographs::graphic('{ "text-footer": { "text": "7", "font-size": "50px" }, "proportion": "0.33", "variableImage": { "clip": "fromright", "preserveAspectRatio": "xMaxYMid meet", "type": "url", "url": "/images/green_rectangle_600_900.jpg" }, "background-color": "yellow", "image-background-color": "pink", "resizable": "false"}')
