// Generated by CoffeeScript 1.8.0
var LabelCell,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

LabelCell = (function(_super) {
  __extends(LabelCell, _super);

  function LabelCell() {
    return LabelCell.__super__.constructor.apply(this, arguments);
  }

  LabelCell.prototype.setConfig = function(config) {
    this.config = config;
    this.labels = [];
    if (_.isString(this.config)) {
      this.labels = [
        {
          text: this.config
        }
      ];
      this.config = {};
    } else if (_.isArray(this.config)) {
      this.labels = this.config.map(function(labelConfig) {
        if (_.isString(labelConfig)) {
          return {
            text: labelConfig
          };
        } else {
          return labelConfig;
        }
      });
      this.config = {};
    } else if (_.has(this.config, 'labels')) {
      this.labels = this.config.labels.map(function(labelConfig) {
        if (_.isString(labelConfig)) {
          return {
            text: labelConfig
          };
        } else {
          return labelConfig;
        }
      });
    } else {
      this.labels = [this.config];
    }
    this._verifyKeyIsInt(this.config, 'padding-top', 0);
    this._verifyKeyIsInt(this.config, 'padding-inner', 0);
    return _.forEach(this.labels, (function(_this) {
      return function(labelConfig, index) {
        if (labelConfig['class'] == null) {
          labelConfig['class'] = "label-" + index;
        }
        if (labelConfig['font-size'] == null) {
          labelConfig['font-size'] = BaseCell.getDefault('font-size');
        }
        return _.forEach(labelConfig, function(labelValue, labelKey) {
          if (labelKey === 'class' || labelKey === 'text') {
            return;
          }
          return _this.setCss(labelConfig['class'], labelKey, labelValue);
        });
      };
    })(this));
  };

  LabelCell.prototype._draw = function() {
    var currentY;
    currentY = this.config['padding-top'];
    return _.forEach(this.labels, (function(_this) {
      return function(labelConfig) {
        var fontSize, labelCenter;
        fontSize = parseInt(labelConfig['font-size'].replace(/(px|em)/, ''));
        labelCenter = {
          x: _this.width / 2,
          y: currentY + fontSize / 2
        };
        _this._addTextTo(_this.parentSvg, labelConfig['text'], labelConfig['class'], labelCenter.x, labelCenter.y);
        return currentY += fontSize + _this.config['padding-inner'];
      };
    })(this));
  };

  LabelCell.prototype._addTextTo = function(parent, text, myClass, x, y) {
    return parent.append('svg:text').attr('class', myClass).attr('x', x).attr('y', y).style('text-anchor', 'middle').style('alignment-baseline', 'central').style('dominant-baseline', 'central').text(text);
  };

  return LabelCell;

})(BaseCell);
